# SPDX-License-Identifier: Apache-2.0

PROJECT_NAME := carbon_blank
REVISION := rev4
M_CUSTOM_LIBS :=
M_ADI_LIBS :=
M_REPOS :=
M_DEPS :=

include ../../../common/carbon/$(REVISION)/scripts/carbon.mk
include ../../scripts/blank_proj.mk
