# SPDX-License-Identifier: Apache-2.0

# ad9361 master

set_property  -dict {PACKAGE_PIN  D4    IOSTANDARD LVDS    DIFF_TERM_ADV TERM_100} [get_ports rx_clk_in_0_p]
set_property  -dict {PACKAGE_PIN  C4    IOSTANDARD LVDS    DIFF_TERM_ADV TERM_100} [get_ports rx_clk_in_0_n]
set_property  -dict {PACKAGE_PIN  F2    IOSTANDARD LVDS    DIFF_TERM_ADV TERM_100} [get_ports rx_frame_in_0_p]
set_property  -dict {PACKAGE_PIN  E2    IOSTANDARD LVDS    DIFF_TERM_ADV TERM_100} [get_ports rx_frame_in_0_n]
set_property  -dict {PACKAGE_PIN  D7    IOSTANDARD LVDS    DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_0_p[0]]
set_property  -dict {PACKAGE_PIN  D6    IOSTANDARD LVDS    DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_0_n[0]]
set_property  -dict {PACKAGE_PIN  F8    IOSTANDARD LVDS    DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_0_p[1]]
set_property  -dict {PACKAGE_PIN  E8    IOSTANDARD LVDS    DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_0_n[1]]
set_property  -dict {PACKAGE_PIN  G3    IOSTANDARD LVDS    DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_0_p[2]]
set_property  -dict {PACKAGE_PIN  F3    IOSTANDARD LVDS    DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_0_n[2]]
set_property  -dict {PACKAGE_PIN  G6    IOSTANDARD LVDS    DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_0_p[3]]
set_property  -dict {PACKAGE_PIN  F6    IOSTANDARD LVDS    DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_0_n[3]]
set_property  -dict {PACKAGE_PIN  E4    IOSTANDARD LVDS    DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_0_p[4]]
set_property  -dict {PACKAGE_PIN  E3    IOSTANDARD LVDS    DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_0_n[4]]
set_property  -dict {PACKAGE_PIN  E5    IOSTANDARD LVDS    DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_0_p[5]]
set_property  -dict {PACKAGE_PIN  D5    IOSTANDARD LVDS    DIFF_TERM_ADV TERM_100} [get_ports rx_data_in_0_n[5]]
set_property  -dict {PACKAGE_PIN  B4    IOSTANDARD LVDS}   [get_ports tx_clk_out_0_p]
set_property  -dict {PACKAGE_PIN  A4    IOSTANDARD LVDS}   [get_ports tx_clk_out_0_n]
set_property  -dict {PACKAGE_PIN  A7    IOSTANDARD LVDS}   [get_ports tx_frame_out_0_p]
set_property  -dict {PACKAGE_PIN  A6    IOSTANDARD LVDS}   [get_ports tx_frame_out_0_n]
set_property  -dict {PACKAGE_PIN  A9    IOSTANDARD LVDS}   [get_ports tx_data_out_0_p[0]]
set_property  -dict {PACKAGE_PIN  A8    IOSTANDARD LVDS}   [get_ports tx_data_out_0_n[0]]
set_property  -dict {PACKAGE_PIN  C8    IOSTANDARD LVDS}   [get_ports tx_data_out_0_p[1]]
set_property  -dict {PACKAGE_PIN  B8    IOSTANDARD LVDS}   [get_ports tx_data_out_0_n[1]]
set_property  -dict {PACKAGE_PIN  C6    IOSTANDARD LVDS}   [get_ports tx_data_out_0_p[2]]
set_property  -dict {PACKAGE_PIN  B6    IOSTANDARD LVDS}   [get_ports tx_data_out_0_n[2]]
set_property  -dict {PACKAGE_PIN  E9    IOSTANDARD LVDS}   [get_ports tx_data_out_0_p[3]]
set_property  -dict {PACKAGE_PIN  D9    IOSTANDARD LVDS}   [get_ports tx_data_out_0_n[3]]
set_property  -dict {PACKAGE_PIN  G8    IOSTANDARD LVDS}   [get_ports tx_data_out_0_p[4]]
set_property  -dict {PACKAGE_PIN  F7    IOSTANDARD LVDS}   [get_ports tx_data_out_0_n[4]]
set_property  -dict {PACKAGE_PIN  G5    IOSTANDARD LVDS}   [get_ports tx_data_out_0_p[5]]
set_property  -dict {PACKAGE_PIN  F5    IOSTANDARD LVDS}   [get_ports tx_data_out_0_n[5]]

set_property  -dict {PACKAGE_PIN  E1    IOSTANDARD LVCMOS18}  [get_ports gpio_status_0[0]]
set_property  -dict {PACKAGE_PIN  D1    IOSTANDARD LVCMOS18}  [get_ports gpio_status_0[1]]
set_property  -dict {PACKAGE_PIN  C3    IOSTANDARD LVCMOS18}  [get_ports gpio_status_0[2]]
set_property  -dict {PACKAGE_PIN  C2    IOSTANDARD LVCMOS18}  [get_ports gpio_status_0[3]]
set_property  -dict {PACKAGE_PIN  B5    IOSTANDARD LVCMOS18}  [get_ports gpio_status_0[4]]
set_property  -dict {PACKAGE_PIN  A5    IOSTANDARD LVCMOS18}  [get_ports gpio_status_0[5]]
set_property  -dict {PACKAGE_PIN  A2    IOSTANDARD LVCMOS18}  [get_ports gpio_status_0[6]]
set_property  -dict {PACKAGE_PIN  A1    IOSTANDARD LVCMOS18}  [get_ports gpio_status_0[7]]
set_property  -dict {PACKAGE_PIN  C1    IOSTANDARD LVCMOS18}  [get_ports gpio_ctl_0[0]]
set_property  -dict {PACKAGE_PIN  B1    IOSTANDARD LVCMOS18}  [get_ports gpio_ctl_0[1]]
set_property  -dict {PACKAGE_PIN  B3    IOSTANDARD LVCMOS18}  [get_ports gpio_ctl_0[2]]
set_property  -dict {PACKAGE_PIN  A3    IOSTANDARD LVCMOS18}  [get_ports gpio_ctl_0[3]]
set_property  -dict {PACKAGE_PIN  B9    IOSTANDARD LVCMOS18}  [get_ports gpio_en_agc_0]
set_property  -dict {PACKAGE_PIN  J1    IOSTANDARD LVCMOS18}  [get_ports mcs_sync]
set_property  -dict {PACKAGE_PIN  E13   IOSTANDARD LVCMOS18}  [get_ports gpio_resetb_0]
set_property  -dict {PACKAGE_PIN  F1    IOSTANDARD LVCMOS18}  [get_ports enable_0]
set_property  -dict {PACKAGE_PIN  G1    IOSTANDARD LVCMOS18}  [get_ports txnrx_0]

set_property  -dict {PACKAGE_PIN  C9    IOSTANDARD LVCMOS18}  [get_ports ad_clk_out_0]
set_property  -dict {PACKAGE_PIN  A11   IOSTANDARD LVCMOS18}  [get_ports ad_rfic_gpo_0[0]]
set_property  -dict {PACKAGE_PIN  A12   IOSTANDARD LVCMOS18}  [get_ports ad_rfic_gpo_0[1]]
set_property  -dict {PACKAGE_PIN  A13   IOSTANDARD LVCMOS18}  [get_ports ad_rfic_gpo_0[2]]
set_property  -dict {PACKAGE_PIN  B13   IOSTANDARD LVCMOS18}  [get_ports ad_rfic_gpo_0[3]]

set_property  -dict {PACKAGE_PIN  L3    IOSTANDARD LVCMOS18}  [get_ports ad_clk_ref]

# clocks

create_clock -name rx_0_clk       -period   4.00 [get_ports rx_clk_in_0_p]
