# SPDX-License-Identifier: Apache-2.0

PROJECT_NAME := carbon-carp_blank
REVISION := rev4.1
M_CUSTOM_LIBS :=
M_ADI_LIBS :=
M_REPOS :=
M_DEPS :=

include ../../../common/carbon-carp/$(REVISION)/scripts/carbon-carp.mk
include ../../scripts/blank_proj.mk
