PROJECT_NAME := carbon_default
REVISION := rev4
M_CUSTOM_LIBS :=
M_ADI_LIBS :=
M_REPOS :=
M_DEPS :=

include ../../../common/carbon/$(REVISION)/scripts/carbon.mk
include ../../scripts/default_proj.mk
